### ISSUE TITLE
Invalid Syntax on Message format

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [logstash-plugins/logstash-codec-line#8]
Not sure if this is a problem with the file output, the line codec, or the documentation!  

Tested Logstash 2.2.0 and 2.3.1

The following syntax, as suggested in the [file output docs](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-file.html)

```
output {
 file {
   path => "./output"
   codec => {
        line {
                format => "custom format: %{message}"
        }
   }
 }
}
```

Results in:

```
Error: Expected one of #, => at line 22, column 7 (byte 294) after output {
 file {
   path => "./output"
   codec => {
	line
```

**Comment by jordansissel** [comment]
Yeah this is a mistake in the docs. Good catch!

**Comment by kxr** [comment]
I am facing the same problem. I've upgraded to logstash 2.3 and the following output configuration:
```
output {
 file {
  path => "/var/log/test.log"
  message_format => "custom format: %{[message]}"
 }

```
 generates the following warning:
```
You are using a deprecated config setting \"message_format\" set in file. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future. You can achieve the same behavior with the 'line' codec If you have any questions about this, please visit the #logstash channel on freenode irc.
```

I am trying to use the line codec in the file output:
```
output {
 file {
  path => "/var/log/test.log"
  codec => { line { format => "custom format: %{message}"}}
 }
```
Which is throws the following configuration error :
```
The given configuration is invalid. Reason: Expected one of #, => at line xx, column xx
```

What would be the correct way to use the line codec in file output?

**Comment by kxr** [comment]
Got it, it was a missing "=>" after "line". The following configuration works:
```

output {
 file {
  path => "/var/log/test.log"
  codec => { line => { format => "custom format: %{message}"}}
 }
```

**Comment by thakurexsete** [comment]
> Got it, it was a missing "=>" after "line". The following configuration works:

Doesn't help. It gives another error as:
`The error reported is:
  undefined method `on_event' for ["line", {"format"=>"LOG: %{message}"}]:Array`

**Comment by PhaedrusTheGreek** [comment]
This works in Logstash 2.3.2

```
output {
 file {
   path => "./output"
   codec =>  line { format => "custom format: %{message}" }
 }
}
```

**Comment by PhaedrusTheGreek** [comment]
@gonph 

Please open a discussion on our support forums: https://discuss.elastic.co/c/logstash and we will help you there.  If it is found to be a bug, we can resume discussions here.  Feel free to ping me on that discussion with @PhaedrusTheGreek

**Comment by jljorgenson18** [comment]
@gonph 

There is an extra bracket right after ` codec =>` and an extra arrow after `line`. It should go from this

`codec => { line => { format => "custom format: %{message}"}}`

to this

`codec => line { format => "custom format: %{message}" } `

**Comment by danucalovj** [comment]
The problem is the bracket as @jljorgenson18 mentioned. Should be:

`codec => line {
    format => "custom format: %{message}"
}`
